/**
 * The STATUS evidence. Clones THIS repository's committed HEAD into a temp
 * directory, installs with a frozen lockfile, runs the demo, then runs every
 * probe from SPEC.md §4 in that fresh clone. Prints one row per claim and
 * writes out/probes.json in the source repo. Exit 1 if any probe fails.
 * Uncommitted changes are NOT visible to the probes — commit first.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const SRC = resolve(import.meta.dir, "..");
const KEEP = process.env["PROBES_KEEP"] === "1";
const tmp = mkdtempSync(join(tmpdir(), "colophon-probes-"));
const clone = join(tmp, "colophon");

type R = { code: number; out: string; err: string; ms: number };
function sh(cmd: string, cwd = clone, env: Record<string, string> = {}): R {
  const t = Date.now();
  const r = spawnSync("bash", ["-eo", "pipefail", "-c", cmd], { cwd, encoding: "utf8", env: { ...process.env, ...env, CLI: "bun packages/cli/main.ts", OUT: "out/demo" }, maxBuffer: 64 * 1024 * 1024, timeout: 600_000 });
  return { code: r.status ?? -1, out: r.stdout ?? "", err: r.stderr ?? "", ms: Date.now() - t };
}
const lines = (s: string) => s.split("\n").filter((l) => l.trim().length > 0);
const last = (s: string) => lines(s).at(-1) ?? "";
const num = (s: string) => Number(last(s).trim());

console.log(`fresh clone: ${clone}`);
let r = sh(`git clone --quiet "${SRC}" "${clone}"`, tmp);
if (r.code !== 0) throw new Error(`clone failed: ${r.err}`);
const head = sh("git rev-parse --short HEAD").out.trim();
r = sh("bun install --frozen-lockfile");
if (r.code !== 0) throw new Error(`install failed: ${r.err}`);
console.log(`HEAD ${head}; installed with --frozen-lockfile`);
mkdirSync(join(clone, "out", "probe"), { recursive: true });

type Probe = { id: string; cmd: string; env?: Record<string, string>; pass: (r: R) => boolean; show?: (r: R) => string };
const P: Probe[] = [
  { id: "S16", cmd: "bun run demo; (git status --porcelain | grep -v '^?? out/' || true) | wc -l", pass: (r) => r.code === 0 && num(r.out) === 0 && r.ms < 90_000 && /^SIGNATURE: /m.test(r.out), show: (r) => `${(r.ms / 1000).toFixed(1)}s, ${(r.out.match(/^SIGNATURE: /gm) ?? []).length} SIGNATURE lines` },
  { id: "S1", cmd: `jq -r '."$schema", (.required|sort|join(","))' packages/schema/declaration.schema.json`, pass: (r) => r.code === 0 && /2020-12/.test(r.out) && ["id", "name", "owner", "risk_tier", "autonomy_level", "tools", "data_classes", "sandbox", "max_scopes", "kill_switch", "review_due", "control_mappings"].every((f) => last(r.out).split(",").includes(f)) },
  { id: "S2", cmd: `for f in packages/fixtures/declarations/*.yaml; do $CLI declare validate "$f" || exit 1; done; set +e; $CLI declare validate packages/fixtures/declarations/bad/missing-owner.yaml; echo "bad=$?"`, pass: (r) => r.code === 0 && /bad=1/.test(r.out) && /owner/.test(r.out + r.err) },
  { id: "S3", cmd: `$CLI record build packages/fixtures/declarations/evidence-reader.yaml --out out/probe/ && R=$(ls out/probe/*.record.json) && $CLI record verify "$R" --hash-only && jq '.canonical_sha256="0000"' "$R" > out/probe/tampered.json; set +e; $CLI record verify out/probe/tampered.json --hash-only; echo "tampered=$?"; $CLI record verify "$R"; echo "nokey=$?"`, pass: (r) => r.code === 0 && /hashes ok/.test(r.out) && /tampered=1/.test(r.out) && /nokey=1/.test(r.out) },
  { id: "S4", cmd: `set +e; a=0; for b in stale high-no-killswitch auth-unbounded; do $CLI record lint packages/fixtures/records/bad/$b.record.json; [ $? -eq 1 ] && a=$((a+1)); done; echo "bad-rejected=$a"; set -e; for r in $OUT/records/*.record.json; do $CLI record lint "$r" || exit 1; done`, pass: (r) => r.code === 0 && /bad-rejected=3/.test(r.out) },
  { id: "S5", cmd: `R=$(ls $OUT/records/*.record.json | head -1); $CLI record verify "$R" --pubkey $OUT/keys/cosign.pub && cp "$R" out/probe/unsigned.record.json; set +e; $CLI gate serve --record out/probe/unsigned.record.json --pubkey $OUT/keys/cosign.pub --self-test --upstream $CLI upstream demo; echo "gate=$?"`, pass: (r) => r.code === 0 && /signature ok/.test(r.out) && /gate=1/.test(r.out) && /signature/.test(r.err) },
  { id: "S6", cmd: `for f in packages/fixtures/gate-input/*.json; do echo "$(basename $f .json) $(opa eval -f raw -d packages/policy/gate.rego -i $f 'concat(":", [data.colophon.gate.decision.effect, concat(",", data.colophon.gate.decision.rule_ids)])')"; done`, pass: (r) => r.code === 0 && ["in-scope allow:COL-GATE-ALLOW", "unknown-tool deny:COL-GATE-UNKNOWN-TOOL", "scope-expansion deny:COL-GATE-SCOPE", "sandbox-escape deny:COL-GATE-SANDBOX", "data-class deny:COL-GATE-DATACLASS", "destination deny:COL-GATE-DESTINATION", "needs-approval escalate:COL-GATE-APPROVAL"].every((x) => r.out.includes(x)) },
  { id: "S7", cmd: `jq -c 'select(.effect=="deny") | select((.rule_ids|length)==0 or (.reasons|length)==0 or (.reasons[0].field|length)==0)' $OUT/*/trace/*.jsonl | wc -l`, pass: (r) => r.code === 0 && num(r.out) === 0 },
  { id: "S8", cmd: `opa test packages/policy -v 2>&1 | grep -c PASS; opa fmt --list packages/policy`, pass: (r) => r.code === 0 && Number(lines(r.out)[0]) >= 20 && lines(r.out).length === 1, show: (r) => `${lines(r.out)[0]} PASS lines` },
  { id: "S9", cmd: `bun tests/policy-flip.ts 2>/dev/null`, pass: (r) => r.code === 0 && /FLIP: sandbox-escape deny -> allow/.test(r.out) && /ts-diff: 0/.test(r.out) },
  { id: "S10", cmd: `$CLI agent run --scenario packages/fixtures/scenarios/evidence-reader.yaml --record $OUT/records/evidence-reader.record.json --pubkey $OUT/keys/cosign.pub --out out/probe/opa-fail >/dev/null 2>out/probe/opa-fail.err; jq -r '.effect+":"+.rule_ids[0]' out/probe/opa-fail/trace/*.jsonl | sort -u`, env: { COLOPHON_GATE_POLICY: "/nonexistent/gate.rego" }, pass: (r) => r.code === 0 && lines(r.out).filter((l) => l.includes(":")).join(",") === "deny:COL-GATE-OPA-ERROR" },
  { id: "S11", cmd: `bun tests/no-ts-verdicts.ts`, pass: (r) => r.code === 0 && /: 0$/m.test(r.out) },
  { id: "S12", cmd: `$CLI agent run --scenario packages/fixtures/scenarios/evidence-reader.yaml --record $OUT/records/evidence-reader.record.json --pubkey $OUT/keys/cosign.pub --out out/probe/mcp --list-tools 2>/dev/null; jq -cS 'select(.effect=="allow") | [.tool, .args_redacted]' out/probe/mcp/trace/*.jsonl | sort > out/probe/allowed.txt; jq -cS '[.tool, .args]' out/probe/mcp/upstream-calls.jsonl | sort > out/probe/reached.txt; diff out/probe/allowed.txt out/probe/reached.txt && echo same; echo "allowed=$(wc -l < out/probe/allowed.txt | tr -d ' ')"`, pass: (r) => r.code === 0 && /tools: auth\.request_scopes, fs\.read, fs\.write, repo\.list, repo\.read_settings/.test(r.out) && /^same$/m.test(r.out) && Number(/allowed=(\d+)/.exec(r.out)?.[1]) >= 4, show: (r) => `${/allowed=\d+/.exec(r.out)?.[0]}; upstream log identical to allowed decisions` },
  { id: "S13", cmd: `$CLI trace verify $OUT/evidence-reader/trace/*.jsonl`, pass: (r) => r.code === 0 && /schema: ok/.test(r.out) && /sealed: yes/.test(r.out) },
  { id: "S14", cmd: `cp $OUT/evidence-reader/trace/*.jsonl out/probe/t.jsonl; sed -i.bak '3s/"effect":"/"effect":"x/' out/probe/t.jsonl; set +e; $CLI trace verify out/probe/t.jsonl; echo "exit=$?"`, pass: (r) => /exit=1/.test(r.out) && /line 3/.test(r.err + r.out) },
  { id: "S15", cmd: `T=$(grep -o 'FAKE-DEMO-CREDENTIAL[A-Za-z0-9-]*' packages/fixtures/scenarios/evidence-reader.yaml | head -1); (grep -r "$T" out/demo || true) | wc -l; grep -rl "$(printf %s "$T" | shasum -a 256 | cut -c1-64)" out/demo | wc -l`, pass: (r) => r.code === 0 && Number(lines(r.out)[0]) === 0 && Number(lines(r.out)[1]) >= 1, show: (r) => `literal ${lines(r.out)[0]} hits, hash ${lines(r.out)[1]} files` },
  { id: "S41", cmd: `T="gh"; T="\${T}p_$(printf 'Q%.0s' $(seq 1 36))"; jq -nc --arg t "$T" '{hook_event_name:"PreToolUse",session_id:"s41",cwd:"/work",tool_name:"Bash",tool_input:{command:("curl -H \\"Authorization: Bearer "+$t+"\\" https://api.example")},ts:"2026-09-15T00:00:00Z",hook_response:{hookSpecificOutput:{permissionDecision:"allow",permissionDecisionReason:"[CC-HOOK-CWD] ok"}}}' > out/probe/s41.jsonl; $CLI normalize claude-hook out/probe/s41.jsonl --out out/probe/s41 >/dev/null; echo "literal=$(grep -c "$T" out/probe/s41/trace/*.jsonl || true)"; echo "commit=$(grep -c "sha256:$(printf %s "$T" | shasum -a 256 | cut -c1-64)" out/probe/s41/trace/*.jsonl)"; echo "shape=$(jq -r '.args_redacted.command' out/probe/s41/trace/*.jsonl | grep -c 'curl -H "Authorization: Bearer sha256:')"`, pass: (r) => r.code === 0 && /literal=0/.test(r.out) && /commit=[1-9]/.test(r.out) && /shape=1/.test(r.out), show: (r) => lines(r.out).join(" ") },
  { id: "S42", cmd: `bun test tests/packet-refuse.test.ts 2>&1 | tail -3; grep -c 'refusing to sign' packages/cli/packet.ts`, pass: (r) => r.code === 0 && /0 fail/.test(r.out) && num(r.out) >= 1 },
  { id: "S43", cmd: `echo "pwd=$(( $(grep -rlF "$PWD" $OUT/*/bundle 2>/dev/null | wc -l) ))"; echo "home=$(( $(grep -rlF "$HOME" $OUT/*/bundle 2>/dev/null | wc -l) ))"; echo "rel=$(grep -c 'bundle verify out/demo/' $OUT/agentcore-dogwood-live/bundle/report/narrative.md)"`, pass: (r) => r.code === 0 && /pwd=0/.test(r.out) && /home=0/.test(r.out) && /rel=[1-9]/.test(r.out), show: (r) => lines(r.out).join(" ") },
  { id: "S44", cmd: `rm -rf out/probe/hook; while IFS= read -r l; do printf '%s' "$l" | $CLI hook --record $OUT/records/claude-coder.record.json --pubkey $OUT/keys/cosign.pub --trace-dir out/probe/hook 2>/dev/null | jq -r '.hookSpecificOutput.permissionDecision'; done < packages/fixtures/claude-hook/events.jsonl | paste -sd, -; jq -r '.rule_ids[0]' out/probe/hook/cc-live-0001.jsonl | paste -sd, -; $CLI trace verify out/probe/hook/cc-live-0001.jsonl; ls out/probe/hook/cc-live-0001.selftest.json`, pass: (r) => r.code === 0 && /^allow,allow,allow,ask,deny,deny,deny,deny$/m.test(r.out) && /^COL-GATE-ALLOW,COL-GATE-ALLOW,COL-GATE-ALLOW,COL-GATE-APPROVAL,COL-GATE-SANDBOX,COL-GATE-DESTINATION,COL-GATE-SANDBOX,COL-GATE-UNKNOWN-TOOL$/m.test(r.out) && /sealed: yes/.test(r.out) && /selftest\.json$/m.test(r.out), show: (r) => `${lines(r.out)[0]}; ${(r.ms / 1000 / 8).toFixed(2)}s per call` },
  { id: "S45", cmd: `echo 'not json' | $CLI hook --record $OUT/records/claude-coder.record.json --pubkey $OUT/keys/cosign.pub --trace-dir out/probe/hook-fc 2>/dev/null | jq -r '.hookSpecificOutput.permissionDecision'; cp $OUT/records/claude-coder.record.json out/probe/unsigned-cc.record.json; head -1 packages/fixtures/claude-hook/events.jsonl | $CLI hook --record out/probe/unsigned-cc.record.json --pubkey $OUT/keys/cosign.pub --trace-dir out/probe/hook-fc 2>/dev/null | jq -r '.hookSpecificOutput.permissionDecision'; head -1 packages/fixtures/claude-hook/events.jsonl | COLOPHON_GATE_POLICY=/nonexistent/gate.rego $CLI hook --record $OUT/records/claude-coder.record.json --pubkey $OUT/keys/cosign.pub --trace-dir out/probe/hook-fc2 2>/dev/null | jq -r '.hookSpecificOutput.permissionDecisionReason' | cut -c1-20; jq -r '.effect+":"+.rule_ids[0]' out/probe/hook-fc/cc-live-0001.jsonl out/probe/hook-fc2/cc-live-0001.jsonl`, pass: (r) => r.code === 0 && lines(r.out).slice(0, 3).map((l) => l.trim()).join("|") === "deny|deny|[COL-GATE-OPA-ERROR]" && lines(r.out).filter((l) => l === "deny:COL-GATE-OPA-ERROR").length === 2, show: (r) => lines(r.out).join(" ") },
  { id: "S46", cmd: `$CLI seal --session cc-live-0001 --trace-dir out/probe/hook --record $OUT/records/claude-coder.record.json --pubkey $OUT/keys/cosign.pub --key $OUT/keys/cosign.key --password colophon-demo --out out/probe/sealed --name cc-probe | grep -E '^packet|^SIGNATURE'; $CLI bundle verify out/probe/sealed/cc-probe/bundle --pubkey $OUT/keys/cosign.pub | tail -1; $CLI bundle verify $OUT/claude-coder/bundle --pubkey $OUT/keys/cosign.pub | tail -1; grep -c '\\*\\*satisfied\\*\\*' $OUT/claude-coder/bundle/report/narrative.md; grep -c 'PreToolUse hook' $OUT/claude-coder/bundle/report/narrative.md; grep -c 'sealSession' packages/cli/demo.ts`, pass: (r) => r.code === 0 && /controls 9\/9/.test(r.out) && /^SIGNATURE: /m.test(r.out) && (r.out.match(/^verified: /gm) ?? []).length === 2 && /^9$/m.test(r.out), show: (r) => lines(r.out).filter((l) => /^packet|^verified/.test(l)).join(" ") },
  { id: "S47", cmd: `$CLI hook settings --record $OUT/records/claude-coder.record.json --pubkey $OUT/keys/cosign.pub --trace-dir out/hook > out/probe/hook-settings.json; jq -r '.hooks.PreToolUse[0].matcher, .hooks.PreToolUse[0].hooks[0].type, .hooks.PreToolUse[0].hooks[0].timeout, (.hooks.PreToolUse[0].hooks[0].command|split(" ")|.[2])' out/probe/hook-settings.json; bun test tests/hook.test.ts 2>&1 | tail -3`, pass: (r) => r.code === 0 && r.out.startsWith("\ncommand\n30\nhook\n") && /0 fail/.test(r.out) },
  { id: "S48", cmd: `H=$(shasum -a 256 packages/policy/gate.rego | cut -c1-64); echo "trace=$(jq -r '.policy_sha256' $OUT/evidence-reader/trace/*.jsonl $OUT/notifier/trace/*.jsonl $OUT/claude-coder/hook/*.jsonl | sort -u | paste -sd, -)"; echo "gate=$H"; ls $OUT/claude-coder/bundle/policy/gate.rego; echo "bound=$($CLI bundle verify $OUT/claude-coder/bundle --pubkey $OUT/keys/cosign.pub | grep -c '^policy: .* decisions bound to policy/gate.rego')"; rm -rf out/probe/swap1; cp -r $OUT/claude-coder/bundle out/probe/swap1; cp packages/policy/record.rego out/probe/swap1/policy/gate.rego; set +e; $CLI bundle verify out/probe/swap1 --pubkey $OUT/keys/cosign.pub > out/probe/swap1.out 2>&1; echo "swap=$?"; echo "failpolicy=$(grep -c 'FAIL policy:' out/probe/swap1.out)"; echo "failmanifest=$(grep -c 'FAIL manifest:' out/probe/swap1.out)"`, pass: (r) => { const t = /trace=([0-9a-f,]+)/.exec(r.out)?.[1]; const g = /gate=([0-9a-f]+)/.exec(r.out)?.[1]; return !!t && !!g && t === g && /policy\/gate\.rego$/m.test(r.out) && /bound=1/.test(r.out) && /swap=1/.test(r.out) && /failpolicy=[1-9]/.test(r.out) && /failmanifest=[1-9]/.test(r.out); }, show: (r) => lines(r.out).filter((l) => /^(bound|swap|fail)/.test(l)).join(" ") },
  { id: "S49", cmd: `jq -r '.declaration.pep.policies[] | .sha256 + "  " + .path' $OUT/records/colophon-roe.record.json | shasum -a 256 -c --quiet && echo declared-hashes-match; echo "staged=$(ls $OUT/agentcore-dogwood-live/bundle/policy | wc -l | tr -d ' ')"; echo "verify=$($CLI bundle verify $OUT/agentcore-dogwood-live/bundle --pubkey $OUT/keys/cosign.pub | grep -c '^policy: .*3 declared policies staged')"; echo "col11=$(grep -c 'COL-11 .*\\*\\*satisfied\\*\\*' $OUT/agentcore-dogwood-live/bundle/report/narrative.md)"; echo "leak=$(( $(grep -rlE '[0-9]{12}|jose-admin' packages/fixtures/agentcore-dogwood 2>/dev/null | wc -l) ))"; rm -rf out/probe/swap2; cp -r $OUT/agentcore-dogwood-live/bundle out/probe/swap2; sed -i.bak 's/within 1h/within 2h/' out/probe/swap2/policy/permit_sensitive_after_approval-uvlil0uj9e.cedar; rm out/probe/swap2/policy/*.bak; set +e; $CLI bundle verify out/probe/swap2 --pubkey $OUT/keys/cosign.pub > out/probe/swap2.out 2>&1; echo "swap=$?"; echo "failpolicy=$(grep -c 'FAIL policy:' out/probe/swap2.out)"`, pass: (r) => /declared-hashes-match/.test(r.out) && /staged=3/.test(r.out) && /verify=1/.test(r.out) && /col11=1/.test(r.out) && /leak=0/.test(r.out) && /swap=1/.test(r.out) && /failpolicy=[1-9]/.test(r.out), show: (r) => lines(r.out).join(" ") },
  { id: "S50", cmd: `echo "catalog=$(grep -c 'id: COL-11' packages/catalog/controls.yaml)"; echo "sat=$(for p in evidence-reader notifier claude-coder agentcore-dogwood-live; do grep -c 'COL-11 .*\\*\\*satisfied\\*\\*' $OUT/$p/bundle/report/narrative.md; done | paste -sd, -)"; echo "unsat=$(for p in claude-hook aws-config agentcore-dogwood; do grep -c 'COL-11 .*\\*\\*not-satisfied\\*\\*' $OUT/$p/bundle/report/narrative.md; done | paste -sd, -)"; bun tests/catalog-shape.ts | grep '^controls:'; bun test tests/packet-refuse.test.ts 2>&1 | tail -3`, pass: (r) => r.code === 0 && /catalog=1/.test(r.out) && /sat=1,1,1,1/.test(r.out) && /unsat=1,1,1/.test(r.out) && /controls: 11/.test(r.out) && /0 fail/.test(r.out), show: (r) => lines(r.out).slice(0, 4).join(" ") },
  { id: "S17", cmd: `jq -r 'select(.effect=="deny").rule_ids[]' $OUT/evidence-reader/trace/*.jsonl | sort -u; echo ---; jq -r 'select(.effect=="allow").tool' $OUT/notifier/trace/*.jsonl | sort -u; echo ---; jq -r 'select(.effect=="deny").rule_ids[]' $OUT/notifier/trace/*.jsonl | sort -u`, pass: (r) => { const s = r.out.split("---"); return r.code === 0 && ["COL-GATE-DATACLASS", "COL-GATE-SANDBOX", "COL-GATE-SCOPE", "COL-GATE-UNKNOWN-TOOL"].every((x) => s[0]!.includes(x)) && s[1]!.includes("fs.write") && s[1]!.includes("mail.send") && s[2]!.includes("COL-GATE-DESTINATION"); } },
  { id: "S18", cmd: `bun run demo >/dev/null && bun run demo >/dev/null && echo twice-ok`, pass: (r) => r.code === 0 && /twice-ok/.test(r.out) },
  { id: "S19", cmd: `set +e; bun run demo --out out/probe/signfail > out/probe/sf.out 2> out/probe/sf.err; echo "exit=$?"; echo "sig-lines=$(grep -c '^SIGNATURE:' out/probe/sf.out)"; echo "cosign-mentions=$(grep -ci cosign out/probe/sf.err)"; echo "packaged=$(ls out/probe/signfail/evidence-reader/bundle/manifest.json out/probe/signfail/evidence-reader/trace/*.jsonl 2>/dev/null | wc -l | tr -d ' ')"; echo "bundles=$(ls out/probe/signfail/*/bundle/*.sigstore.json 2>/dev/null | wc -l | tr -d ' ')"`, env: { COLOPHON_COSIGN_BIN: join(clone, "tests", "fake-cosign-signfail.sh") }, pass: (r) => /exit=1/.test(r.out) && /sig-lines=0/.test(r.out) && !/cosign-mentions=0/.test(r.out) && /packaged=2/.test(r.out) && /bundles=0/.test(r.out), show: (r) => lines(r.out).join(" ") },
  { id: "S20", cmd: `bun test tests/evidence.test.ts 2>&1 && grep -c 'duplicate\\|mismatch' tests/evidence.test.ts`, pass: (r) => r.code === 0 && /0 fail/.test(r.out) && num(r.out) >= 2 },
  { id: "S21", cmd: `bun tests/catalog-shape.ts`, pass: (r) => r.code === 0 && /themes: 8\/8/.test(r.out) && Number(/controls: (\d+)/.exec(r.out)?.[1]) >= 8 },
  { id: "S22", cmd: `$CLI report validate $OUT/evidence-reader/bundle/report/assessment-results.json`, pass: (r) => r.code === 0 && /oscal-version: 1\.2\.3/.test(r.out) },
  { id: "S23", cmd: `$CLI bundle verify $OUT/evidence-reader/bundle --pubkey $OUT/keys/cosign.pub`, pass: (r) => r.code === 0 && Number(/rlinks: (\d+) resolved/.exec(r.out)?.[1]) >= 1 && /unresolved: 0/.test(r.out) && /bound to verified record/.test(r.out) },
  { id: "S24", cmd: `bun test tests/citation.test.ts 2>&1 && grep -c 'refuses' tests/citation.test.ts`, pass: (r) => r.code === 0 && /0 fail/.test(r.out) && num(r.out) >= 1 },
  { id: "S25", cmd: `grep -c 'Judgment is not' $OUT/evidence-reader/bundle/report/narrative.md; grep -ci 'does not prove' $OUT/evidence-reader/bundle/report/narrative.md; grep -ci vacuous $OUT/evidence-reader/bundle/report/narrative.md || true`, pass: (r) => { const n = lines(r.out).map(Number); return n[0]! >= 1 && n[1]! >= 1 && n[2] === 0; } },
  { id: "S26", cmd: `$CLI report --trace packages/fixtures/traces/breach.jsonl --record $OUT/records/evidence-reader.record.json --out out/probe/breach >/dev/null; jq '[."assessment-results".results[].findings[] | select(.target.status.state=="not-satisfied")] | length' out/probe/breach/report/assessment-results.json; jq -r '."assessment-results".results[].findings[] | select(.target.status.state=="not-satisfied") | .title' out/probe/breach/report/assessment-results.json`, pass: (r) => r.code === 0 && Number(lines(r.out)[0]) >= 1 && /COL-05/.test(r.out), show: (r) => lines(r.out).slice(1).join("; ") },
  { id: "S27", cmd: `jq -r '.root_sha256, (.files|length)' $OUT/evidence-reader/bundle/manifest.json; set +e; $CLI bundle create --from $OUT/evidence-reader/stage --out $OUT/evidence-reader/bundle; echo "again=$?"`, pass: (r) => /^[0-9a-f]{64}$/m.test(r.out) && Number(lines(r.out)[1]) >= 4 && /again=1/.test(r.out) },
  { id: "S28", cmd: `rm -rf out/probe/b out/probe/b2 out/probe/b4; cp -r $OUT/evidence-reader/bundle out/probe/b && printf x >> out/probe/b/report/narrative.md; set +e; $CLI bundle verify out/probe/b --pubkey $OUT/keys/cosign.pub; echo "tamper=$?"; cp -r $OUT/evidence-reader/bundle out/probe/b2 && touch out/probe/b2/extra.txt; $CLI bundle verify out/probe/b2 --pubkey $OUT/keys/cosign.pub; echo "extra=$?"; cp -r $OUT/evidence-reader/bundle out/probe/b4 && rm out/probe/b4/session.json; $CLI bundle verify out/probe/b4 --pubkey $OUT/keys/cosign.pub; echo "removed=$?"`, pass: (r) => /tamper=1/.test(r.out) && /extra=1/.test(r.out) && /removed=1/.test(r.out) && /narrative\.md/.test(r.err) && /extra\.txt/.test(r.err) && /session\.json/.test(r.err) },
  { id: "S29", cmd: `ls $OUT/evidence-reader/bundle/manifest.sigstore.json && rm -rf out/probe/b3 && cp -r $OUT/evidence-reader/bundle out/probe/b3 && rm out/probe/b3/manifest.sigstore.json; set +e; $CLI bundle verify out/probe/b3 --pubkey $OUT/keys/cosign.pub; echo "missing=$?"`, pass: (r) => /manifest\.sigstore\.json$/m.test(r.out) && /missing=1/.test(r.out) && /manifest\.sigstore\.json missing/.test(r.err) },
  { id: "S30", cmd: `$CLI bundle verify $OUT/evidence-reader/bundle --pubkey $OUT/keys/cosign.pub --out out/probe/vr && $CLI report validate out/probe/vr/verification-results.json && jq -r '."assessment-results".results[].findings[].title' out/probe/vr/verification-results.json`, pass: (r) => r.code === 0 && /COL-08/.test(r.out) && /COL-09/.test(r.out) && /oscal-version: 1\.2\.3/.test(r.out) },
  { id: "S31", cmd: `$CLI normalize claude-hook packages/fixtures/claude-hook/session.jsonl --out out/probe/ch && $CLI trace verify out/probe/ch/trace/*.jsonl && jq -r '.source' out/probe/ch/trace/*.jsonl | sort -u && $CLI bundle verify $OUT/claude-hook/bundle --pubkey $OUT/keys/cosign.pub`, pass: (r) => r.code === 0 && /^claude-hook$/m.test(r.out) && /verified:/.test(r.out) },
  { id: "S32", cmd: `$CLI normalize aws-config packages/fixtures/aws --out out/probe/aws && jq -r '.effect' out/probe/aws/trace/*.jsonl | sort | uniq -c; echo "deps=$(jq -r '(.dependencies + .devDependencies)|keys[]' package.json | grep -c aws || true)"; echo "live=$(grep -rn 'LiveAws\\|@aws-sdk' packages | wc -l | tr -d ' ')"`, pass: (r) => r.code === 0 && /allow/.test(r.out) && /deny/.test(r.out) && /deps=0/.test(r.out) && /live=0/.test(r.out) },
  { id: "S38", cmd: `$CLI normalize agentcore-dogwood packages/fixtures/agentcore-dogwood/session.jsonl --out out/probe/ac && $CLI trace verify out/probe/ac/trace/*.jsonl && jq -r '.source' out/probe/ac/trace/*.jsonl | sort -u && jq -r 'select(.effect=="deny").rule_ids[]' out/probe/ac/trace/*.jsonl | sort -u && $CLI bundle verify $OUT/agentcore-dogwood/bundle --pubkey $OUT/keys/cosign.pub && $CLI normalize agentcore-dogwood packages/fixtures/agentcore-dogwood/no-decision.jsonl --out out/probe/ac-fc && jq -r 'select(.effect=="deny").rule_ids[]' out/probe/ac-fc/trace/*.jsonl | sort -u; echo "deps=$(jq -r '(.dependencies + .devDependencies)|keys[]' package.json | grep -cE 'aws-sdk|bedrock' || true)"; echo "live=$(grep -rnE 'LiveAws|@aws-sdk' packages/adapters/agentcore-dogwood --include='*.ts' | wc -l | tr -d ' ')"`, pass: (r) => r.code === 0 && /^agentcore-dogwood$/m.test(r.out) && /verified:/.test(r.out) && /DW-APPROVE-BEFORE-ACT/.test(r.out) && /DW-OUT-OF-SCOPE/.test(r.out) && /DW-RATE-LIMIT/.test(r.out) && /AGENTCORE-NO-DECISION/.test(r.out) && /deps=0/.test(r.out) && /live=0/.test(r.out) },
  { id: "S39", cmd: `$CLI normalize agentcore-dogwood packages/fixtures/agentcore-dogwood/session.jsonl --out out/probe/ac-find && $CLI export finding --from out/probe/ac-find --out out/probe/findings && $CLI export finding validate out/probe/findings/*.finding.json && jq -r '.schema_version, .source, .resource.type, .resource.id' out/probe/findings/*.finding.json && $CLI export finding validate $OUT/agentcore-dogwood/findings/*.finding.json && echo "col01=$(jq -r '.evaluations[].control_id' $OUT/agentcore-dogwood/findings/*.finding.json | grep -c '^COL-01$' || true)" && echo "scf=$(jq -r '.evaluations[].control_framework' $OUT/agentcore-dogwood/findings/*.finding.json | grep -c SCF || true)" && echo "in-manifest=$(jq -r '.files[].path' $OUT/agentcore-dogwood/bundle/manifest.json | grep -c findings || true)"`, pass: (r) => r.code === 0 && /finding.schema.json v1\.0\.0/.test(r.out) && /ai_agent_session:ac-roe-0001/.test(r.out) && /colophon-agentcore-dogwood/.test(r.out) && /col01=1/.test(r.out) && /scf=0/.test(r.out) && /in-manifest=0/.test(r.out) },
  { id: "S40", cmd: `$CLI normalize agentcore-dogwood packages/fixtures/agentcore-dogwood/live-roe-7461903f.jsonl --out out/probe/ac-live && $CLI trace verify out/probe/ac-live/trace/*.jsonl && jq -r '.effect+":"+.rule_ids[0]+":"+.tool' out/probe/ac-live/trace/*.jsonl && jq -r '.session_id' out/probe/ac-live/trace/*.jsonl | sort -u && $CLI export finding --from out/probe/ac-live --out out/probe/ac-live-findings && $CLI export finding validate out/probe/ac-live-findings/*.finding.json && $CLI bundle verify $OUT/agentcore-dogwood-live/bundle --pubkey $OUT/keys/cosign.pub && $CLI export finding validate $OUT/agentcore-dogwood-live/findings/*.finding.json; echo "sid=$(jq -r '.resource.id' $OUT/agentcore-dogwood-live/findings/*.finding.json)"; echo "col05=$(grep -c 'COL-05 .*\\*\\*satisfied\\*\\*' $OUT/agentcore-dogwood-live/bundle/report/narrative.md || true)"; echo "reqid-bound=$(grep -c 'request_id.*fell outside' $OUT/agentcore-dogwood-live/bundle/report/narrative.md || true)"; mkdir -p out/probe/ac-nometasrc && cp packages/fixtures/agentcore-dogwood/live-roe-7461903f.jsonl out/probe/ac-nometasrc/; set +e; $CLI normalize agentcore-dogwood out/probe/ac-nometasrc/live-roe-7461903f.jsonl --out out/probe/ac-nometa; echo "nometa=$?"; set -e; $CLI normalize agentcore-dogwood out/probe/ac-nometasrc/live-roe-7461903f.jsonl --session 7461903f-e0c0-41ce-844b-87d43dcb1a23 --out out/probe/ac-flag && jq -r '.session_id' out/probe/ac-flag/trace/*.jsonl | sort -u; echo "deps=$(jq -r '(.dependencies + .devDependencies)|keys[]' package.json | grep -cE 'aws-sdk|bedrock' || true)"; echo "live=$(grep -rnE 'LiveAws|@aws-sdk' packages/adapters/agentcore-dogwood --include='*.ts' | wc -l | tr -d ' ')"`, pass: (r) => {
    const seq = lines(r.out).filter((l) => /^(allow|deny):/.test(l));
    return (
      r.code === 0 &&
      seq.join("\n") ===
        [
          "allow:permit_get_status_scoped-zn8oczkgdi:StatusTarget___get_status",
          "deny:AGENTCORE-DEFAULT-DENY:StatusTarget___do_sensitive",
          "allow:permit_approve_action_scoped-jmopu2crfw:StatusTarget___approve_action",
          "allow:permit_sensitive_after_approval-uvlil0uj9e:StatusTarget___do_sensitive",
          "deny:AGENTCORE-DEFAULT-DENY:StatusTarget___do_sensitive",
        ].join("\n") &&
      /7461903f-e0c0-41ce-844b-87d43dcb1a23/.test(r.out) &&
      /finding.schema.json v1\.0\.0/.test(r.out) &&
      /verified:/.test(r.out) &&
      /col05=1/.test(r.out) &&
      /reqid-bound=0/.test(r.out) &&
      /nometa=1/.test(r.out) &&
      /deps=0/.test(r.out) &&
      /live=0/.test(r.out)
    );
  }, show: (r) => lines(r.out).filter((l) => /^(allow|deny):|nometa=|deps=|live=|sid=|col05=|reqid-bound=/.test(l)).join(" ") },
  { id: "S33", cmd: `grep -c 'Custody is provable. Judgment is not.' README.md; grep -c 'bun install && bun run demo' README.md; grep -c 'bundle verify' README.md; grep -c 'STATUS.md' README.md`, pass: (r) => r.code === 0 && lines(r.out).every((l) => Number(l) >= 1) },
  { id: "S34", cmd: `grep -cE '^\\| (S[0-9]+|A[0-9]+) ' STATUS.md`, pass: (r) => num(r.out) === 53 },
  { id: "S35", cmd: `grep -ci 'operator brief' DECISIONS.md || true; grep -c '^### ' DECISIONS.md`, pass: (r) => Number(lines(r.out)[0]) === 0 && Number(lines(r.out)[1]) >= 8 },
  { id: "S36", cmd: `bun test tests 2>&1 | tail -3; bun run typecheck`, pass: (r) => r.code === 0 && /0 fail/.test(r.out) },
  { id: "S37", cmd: `grep -E 'cosign-installer|cosign-release|bun-version|frozen-lockfile|opa test|bun run demo|probes.ts|sigstore.json|bundle verify|certificate-identity' .github/workflows/ci.yml | wc -l`, pass: (r) => num(r.out) >= 9 },
  { id: "A1", cmd: `grep -rnE 'signed\\.ok|fallback|stopgap' packages --include=*.ts | wc -l`, pass: (r) => num(r.out) === 0 },
  { id: "A2", cmd: `jq -r '(.dependencies + .devDependencies)|keys[]' package.json | grep -ciE 'openai|anthropic|aws-sdk|google-ai|bedrock' || true`, pass: (r) => num(r.out) === 0 },
  { id: "A3", cmd: `gitleaks detect --no-git --config .gitleaks.toml --exit-code 1 -v 2>&1 | tail -2`, pass: (r) => r.code === 0 && /no leaks found/.test(r.out) },
];

const results: { id: string; pass: boolean; ms: number; detail: string }[] = [];
for (const p of P) {
  const r = sh(p.cmd, clone, p.env);
  const ok = p.pass(r);
  const detail = p.show ? p.show(r) : (last(r.out) || last(r.err)).slice(0, 100);
  results.push({ id: p.id, pass: ok, ms: r.ms, detail });
  console.log(`${ok ? "PASS" : "FAIL"} ${p.id.padEnd(4)} ${(r.ms / 1000).toFixed(1).padStart(6)}s  ${detail}`);
  if (!ok) console.log(`     exit=${r.code}\n     stdout: ${r.out.trim().split("\n").slice(-6).join("\n             ")}\n     stderr: ${r.err.trim().split("\n").slice(-6).join("\n             ")}`);
}
const failed = results.filter((x) => !x.pass);
mkdirSync(join(SRC, "out"), { recursive: true });
writeFileSync(join(SRC, "out", "probes.json"), JSON.stringify({ head, ran_at: new Date().toISOString(), clone, results }, null, 2) + "\n");
console.log(`\n${results.length - failed.length}/${results.length} probes pass at HEAD ${head}${failed.length ? ` — FAILED: ${failed.map((f) => f.id).join(", ")}` : ""}`);
if (!KEEP) spawnSync("rm", ["-rf", tmp]);
process.exit(failed.length ? 1 : 0);
